name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup shfmt
      uses: mfinelli/setup-shfmt@v3

    - name: Run shfmt
      run: shfmt -i 4 -d ./src/ ./tests/

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master

    - name: Set up Bats
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        sudo ./install.sh /usr/local

    - name: Run tests
      run: bats -T ./tests
